jobs:
  - template: cicd/templates/build-android.yml
    parameters:
      displayName: 'ChatRoomAndroid'
      workingDirectory: 'Android'
      rtcSdkUrl: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Android_v3_1_0_VOICE.zip?_ga=2.213530388.1493357375.1597372715-269570672.1596526126'
      rtmSdkUrl: 'https://download.agora.io/rtmsdk/release/Agora_RTM_SDK_for_Android_v1_2_2.zip'

  - template: cicd/templates/build-ios.yml
    parameters:
      displayName: 'ChatRoomIos'
      workingDirectory: 'iOS'
      rtcSdkUrl: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v3_1_0_VOICE.zip?_ga=2.52976808.1493357375.1597372715-269570672.1596526126'
      rtmSdkUrl: 'https://download.agora.io/rtmsdk/release/Agora_RTM_SDK_for_iOS_v1_2_2.zip'
