parameters:
  displayName: ''
  workingDirectory: ''
  rtcSdkUrl: ''
  rtmSdkUrl: ''
  scheme: 'AgoraChatRoom'

jobs:
  - job: ${{ parameters.displayName }}_Build
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'macOS-latest'

    variables:
      - group: AgoraKeys
      - name: configuration
        value: 'Release'
      - name: sdk
        value: 'iphoneos'

    steps:
      - script: cd ${{ parameters.workingDirectory }} && ls && python ci.env.py
        env:
          RTC_SDK_URL: ${{ parameters.rtcSdkUrl }}
          RTM_SDK_URL: ${{ parameters.rtmSdkUrl }}
          SCHEME: ${{ parameters.scheme }}
          AGORA_APP_ID: '$(agora.appId)'

      - script: ls ${{ parameters.workingDirectory }}/${{ parameters.scheme }}/libs

      - task: InstallAppleCertificate@2
        inputs:
          certSecureFile: 'certificate.p12'
          certPwd: '$(agora.password)'

      - task: InstallAppleProvisioningProfile@1
        inputs:
          provProfileSecureFile: 'AgoraAppsDevProfile.mobileprovision'

      - task: Xcode@5
        inputs:
          actions: 'build'
          configuration: '$(configuration)'
          sdk: '$(sdk)'
          xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
          scheme: ${{ parameters.scheme }}
          packageApp: 'true'
          exportMethod: 'development'
          signingOption: 'manual'
          signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
          provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
          useXcpretty: 'false'

      - task: CopyFiles@2
        inputs:
          contents: '**/*.ipa'
          targetFolder: '$(build.artifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(build.artifactStagingDirectory)'
          artifactName: ${{ parameters.displayName }}